import axios from "axios";
import jwt from "jsonwebtoken";
import { Website } from "../../models/user";

export default async function verifyWebsite(link, userID, replace = false) {
    /**
     * verificationData : {
     *      owner : userID,
     *      domain : url.origin,
     *      website : websiteID,
     * }
     */
    try {
        const url = new URL(link);
        const domain = url.hostname;

        // Fetch the file
        const response = await axios.get(link, {
            timeout: 10000,
            headers: { "User-Agent": "LinkFixerBot/1.0" },
            responseType: 'text', // Force text response
            validateStatus: (status) => status === 200
        });

        let jwtToken = response.data;

        // Handle different data types
        if (typeof jwtToken !== 'string') {
            return {
                success: false,
                error: 'Verification file must contain plain text JWT token'
            };
        }

        // Clean up the token
        jwtToken = jwtToken
            .trim()
            .replace(/\n/g, '')
            .replace(/\r/g, '')
            .replace(/\s+/g, '')
            .replace(/^\uFEFF/, '');

        // Check if it looks like a JWT (has two dots)
        if ((jwtToken.match(/\./g) || []).length !== 2) {
            return {
                success: false,
                error: 'Invalid JWT format. Token must have format: header.payload.signature'
            };
        }

        // Check for HTML tags (common issue)
        if (jwtToken.includes('<') || jwtToken.includes('>')) {
            return {
                success: false,
                error: 'Verification file contains HTML. Please ensure it contains only the JWT token.'
            };
        }

        const secret = process.env.JWT_VERIFICATION_SECRET;

        // Verify JWT signature
        const decoded = jwt.verify(jwtToken, secret);

        // Normalize domains
        const normalizedDomain = domain.replace(/^www\./, '');
        const normalizedJWTDomain = decoded.domain.replace(/^www\./, '');

        if (normalizedJWTDomain !== normalizedDomain) {
            return {
                success: false,
                error: `Domain mismatch: JWT is for ${decoded.domain}, but file is hosted on ${domain}`
            };
        }

        // Fetch website from database
        const website = await Website.findById(decoded.websiteID);

        if (!website) {
            return {
                success: false,
                error: `Website not found in database`
            };
        }

        if (!website.userID.includes(userID) || decoded.owner !== userID) {
            return {
                success: false,
                error: `Invalid user`
            }
        }

        if (!replace && website.ownerID) {
            return {
                success: false,
                error: `Website already has a owner`
            }
        }

        if(!website.ownerID){
            website.ownerID = userID
            website.verifiedUsers.push(userID)
            await website.save();
            return {
                success: true
            }
        }

        if (replace && website.verifiedUsers.includes(userID)) {
            website.ownerID = userID
            await website.save();
            return {
                success: true
            }
        }
        return {
            success : false,
            error : `New owner must be verified by previous owner`
        }

    } catch (err) {
        // Generated by Claude ------->>>>>>>

        // JWT-specific errors
        if (err.name === 'JsonWebTokenError') {
            return {
                success: false,
                error: `Invalid JWT token. Please ensure the file contains a valid token.`
            };
        }

        if (err.name === 'TokenExpiredError') {
            return {
                success: false,
                error: `JWT token has expired. Please generate a new verification token.`
            };
        }

        // Network errors
        if (err.code === 'ENOTFOUND') {
            return {
                success: false,
                error: `Cannot reach the URL: ${link}`
            };
        }

        if (err.code === 'ECONNREFUSED') {
            return {
                success: false,
                error: `Connection refused to ${link}`
            };
        }

        // HTTP errors
        if (axios.isAxiosError(err)) {
            if (err.response?.status === 404) {
                return {
                    success: false,
                    error: `Verification file not found at ${link}`
                };
            }
            if (err.response?.status === 403) {
                return {
                    success: false,
                    error: `Access forbidden to ${link}`
                };
            }
            return {
                success: false,
                error: `Failed to fetch verification file (HTTP ${err.response?.status})`
            };
        }

        // Invalid URL
        if (err.message?.includes('Invalid URL')) {
            return {
                success: false,
                error: `Invalid URL format: ${link}`
            };
        }

        console.error('Verification error:', err);
        return {
            success: false,
            error: `Verification failed: ${err.message}`
        };
    }
}